### ISSUE TITLE
接口400了

### ISSUE THREAD

**Issue by xuchaoying** [GyrosWorkshop/WukongProvider#30]
这导致听完一首歌就卡了，只能刷新。 每首歌听完都要刷新。

![image](https://user-images.githubusercontent.com/8073251/47404610-93c8db80-d780-11e8-9b1a-7aede664c12f.png)

**Comment by richard1122** [comment]
400 是由于 finish 的歌曲不是后端当前的歌曲，此时后端会重新计算状态，不是 bug

**Comment by Leeleo3x** [comment]
@richard1122 那为啥不close？

**Comment by Leeleo3x** [comment]
@richard1122 不过为啥会和后端不一致呀 不如把请求也发上来？

**Comment by richard1122** [comment]
请求的时候会带上当前歌曲的

**Comment by Leeleo3x** [comment]
@richard1122 我是说xxj
