### ISSUE TITLE
云盘歌曲没法播了！

### ISSUE THREAD

**Issue by xuchaoying** [GyrosWorkshop/WukongProvider#35]

**Comment by Senorsen** [comment]
未提供有效信息：是否正确使用了相关 Cookie 、是否还在有效期、 Wukong 服务器是否有返回、返回的媒体地址是什么、媒体地址（如果有的话）访问后的响应。

**Comment by xuchaoying** [comment]
@Senorsen 这个复现太简单了

**Comment by Senorsen** [comment]
@xuchaoying 用户能否手动请求 provider service ，查看响应？

**Comment by xuchaoying** [comment]
@Senorsen 用户不知道，用户啥都不懂

**Comment by richard1122** [comment]
听说以后都不能播了？

**Comment by xuchaoying** [comment]
@richard1122 你这个是没拿到播放地址吧

**Comment by Senorsen** [comment]
Wukong 已下线
